INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200224	,'TUBO CLASE 16 DE 20 MM','M','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200225	,'TUBO CLASE 16 DE 25 MM','M','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200226	,'TUBO CLASE 16 DE 32 MM','M','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200227	,'TUBO CLASE 16 DE 40 MM','M','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200228	,'TUBO CLASE 16 DE 50 MM','M','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200229	,'TUBO CLASE 16 DE 63 MM','M','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200230	,'TUBO CLASE 16 DE 75 MM','M','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200231	,'TUBO CLASE 16 DE 90 MM','M','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200223	,'TUBO CLASE 16 DE 110 MM','M','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200005	,'CODO A 45 DE 20 MM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200006	,'CODO A 45 DE 25 MM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200007	,'CODO A 45 DE 32 MM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200008	,'CODO A 45 DE 40 MM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200009	,'CODO A 45 DE 50 MM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200010	,'CODO A 45 DE 63 MM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200011	,'CODO A 45 DE 75 MM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200012	,'CODO A 45 DE 90 MM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200004	,'CODO A 45 DE 110 MM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200014	,'CODO A 90 DE 20 MM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200015	,'CODO A 90 DE 25 MM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200016	,'CODO A 90 DE 32 MM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200017	,'CODO A 90 DE 40 MM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200018	,'CODO A 90 DE 50 MM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200019	,'CODO A 90 DE 63 MM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200020	,'CODO A 90 DE 75 MM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200021	,'CODO A 90 DE 90 MM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200013	,'CODO A 90 DE 110 MM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200034	,'CODO MACHO HEMBRA A 45 DE 20 MM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200035	,'CODO MACHO HEMBRA A 45 DE 25 MM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200036	,'CODO MACHO HEMBRA A 45 DE 32 MM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200037	,'CODO MACHO HEMBRA A 90 DE 20 MM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200038	,'CODO MACHO HEMBRA A 90 DE 25 MM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200022	,'CODO 90 CON ROSCA HEMBRA DE 20 MM x 1/2','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200023	,'CODO 90 CON ROSCA HEMBRA DE 25 MM x 1/2','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200024	,'CODO 90 CON ROSCA HEMBRA DE 25 MM x 3/4','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200026	,'CODO 90 CON ROSCA HEMBRA DE 32 MM x 1/2','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200027	,'CODO 90 CON ROSCA HEMBRA DE 32 MM x 3/4','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200025	,'CODO A 90 CON ROSCA HEMBRA DE 32 MM x 1','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200028	,'CODO A 90 CON ROSCA MACHO DE 20 MM X 1/2','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200029	,'CODO A 90 CON ROSCA MACHO DE 25 MM x 1/2','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200030	,'CODO A 90 CON ROSCA MACHO DE 25 MM x 3/4','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200032	,'CODO A 90 CON ROSCA MACHO DE 32 MM x 1/2','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200033	,'CODO A 90 CON ROSCA MACHO DE 32 MM x 3/4','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200031	,'CODO A 90 CON ROSCA MACHO DE 32 MM X 1','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200178	,'TEE DE 20 MM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200179	,'TEE DE 25 MM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200180	,'TEE DE 32 MM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200181	,'TEE DE 40 MM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200182	,'TEE DE 50 MM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200183	,'TEE DE 63 MM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200165	,'TEE DE 75 MM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200184	,'TEE DE 90 MM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200164	,'TEE DE 110 MM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200082	,'CRUZ DE 20 MM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200166	,'TEE C/ROSCA CENTRAL HEMBRA 20 MM x 1/2','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200167	,'TEE C/ROSCA CENTRAL HEMBRA 25 MM x 1/2','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200168	,'TEE C/ROSCA CENTRAL HEMBRA 25 MM x 3/4','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200170	,'TEE C/ROSCA CENTRAL HEMBRA 32 MM x 1/2','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200171	,'TEE C/ROSCA CENTRAL HEMBRA 32 MM x 3/4','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200169	,'TEE C/ROSCA CENTRAL HEMBRA 32 MM x 1','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200172	,'TEE C/ROSCA CENTRAL MACHO  20 MM x 1/2','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200173	,'TEE C/ROSCA CENTRAL MACHO  25 MM x 1/2','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200174	,'TEE C/ROSCA CENTRAL MACHO  25 MM x 3/4','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200176	,'TEE C/ROSCA CENTRAL MACHO  32 MM x 1/2','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200177	,'TEE C/ROSCA CENTRAL MACHO  32 MM x 3/4','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200175	,'TEE CON ROSCA CENTRAL MACHO DE 32 MM x 1','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200185	,'TEE REDUCIDA CENTRAL DE 25 x 20 MM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200186	,'TEE REDUCIDA CENTRAL DE 32 x 20 MM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200187	,'TEE REDUCIDA CENTRAL DE 32 x 25 MM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200188	,'TEE REDUCIDA CENTRAL DE 40 x 25 MM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200189	,'TEE REDUCIDA CENTRAL DE 40 x 32 MM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200190	,'TEE REDUCIDA CENTRAL DE 50 x 32 MM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200191	,'TEE REDUCIDA CENTRAL DE 50 x 40 MM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200192	,'TEE REDUCIDA CENTRAL DE 63 x 40 MM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200193	,'TEE REDUCIDA CENTRAL DE 63 x 50 MM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200194	,'TEE REDUCIDA CENTRAL DE 75 x 50 MM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200195	,'TEE REDUCIDA CENTRAL DE 75 x 63 MM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200196	,'TEE REDUCIDA CENTRAL DE 90 x 63 MM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200197	,'TEE REDUCIDA CENTRAL DE 90 x 75 MM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200198	,'TEE REDUCIDA EXTREMA DE 20 E 25 MM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200200	,'TEE REDUCIDA EXTREMA DE 20 E 32 MM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200199	,'TEE REDUCIDA EXTREMA DE 25 E 20 MM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200202	,'TEE REDUCIDA EXTREMA DE 25 E 32 MM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200201	,'TEE REDUCIDA EXTREMA DE 32 E 20 MM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200203	,'TEE REDUCIDA EXTREMA DE 32 E 25 MM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200205	,'TEE REDUCIDA EXTREMA-CENTRAL 32X25X20 MM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200204	,'TEE REDUCIDA EXTREMA-CENTRAL 32X20X25 MM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200065	,'COPLE DE 20 MM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200066	,'COPLE DE 25 MM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200067	,'COPLE DE 32 MM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200068	,'COPLE DE 40 MM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200069	,'COPLE DE 50 MM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200070	,'COPLE DE 63 MM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200071	,'COPLE DE 75 MM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200072	,'COPLE DE 90 MM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200064	,'COPLE DE 110 MM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200039	,'CONECTOR HEMBRA DE 20 MM x 1/2','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200040	,'CONECTOR HEMBRA DE 20 MM x 3/4','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200041	,'CONECTOR HEMBRA DE 25 MM x 1/2','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200042	,'CONECTOR HEMBRA DE 25 MM x 3/4','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200044	,'CONECTOR HEMBRA DE 32 MM x 3/4','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200043	,'CONECTOR HEMBRA DE 32 MM x 1','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200045	,'CONECTOR HEMBRA DE 40 MM x 1 1/4','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200046	,'CONECTOR HEMBRA DE 50 MM x 1 1/2','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200047	,'CONECTOR HEMBRA DE 63 MM x 2','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200048	,'CONECTOR HEMBRA DE 75 MM x 2 1/2','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200049	,'CONECTOR HEMBRA DE 90 MM x 3','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200051	,'CONECTOR MACHO DE 20 MM x 1/2','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200052	,'CONECTOR MACHO DE 20 MM x 3/4','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200053	,'CONECTOR MACHO DE 25 MM x 1/2','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200054	,'CONECTOR MACHO DE 25 MM x 3/4','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200056	,'CONECTOR MACHO DE 32 MM x 3/4','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200055	,'CONECTOR MACHO DE 32 MM x 1','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200057	,'CONECTOR MACHO DE 40 MM x 1 1/4','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200058	,'CONECTOR MACHO DE 50 MM x 1 1/2','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200059	,'CONECTOR MACHO DE 63 MM x 2','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200060	,'CONECTOR MACHO DE 75 MM x 2 1/2','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200061	,'CONECTOR MACHO DE 90 MM x 3','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200050	,'CONECTOR HEMBRA TERFUS MACHO 20 MM x 1/2','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200062	,'CONECTOR MACHO TERFUS MACHO 20 MM x 1/2','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200140	,'REDUCCION DE 25 x 20 MM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200141	,'REDUCCION DE 32 x 20 MM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200142	,'REDUCCION DE 32 x 25 MM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200143	,'REDUCCION DE 40 x 25 MM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200144	,'REDUCCION DE 40 x 32 MM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200145	,'REDUCCION DE 50 x 32 MM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200146	,'REDUCCION DE 50 x 40 MM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200147	,'REDUCCION DE 63 x 40 MM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200148	,'REDUCCION DE 63 x 50 MM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200149	,'REDUCCION DE 75 x 50 MM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200150	,'REDUCCION DE 75 x 63 MM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200151	,'REDUCCION DE 90 x 63 MM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200152	,'REDUCCION DE 90 x 75 MM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200136	,'REDUCCION CENTRAL 110X50 MM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200137	,'REDUCCION CENTRAL 110X63 MM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200138	,'REDUCCION CENTRAL 110X75','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200139	,'REDUCCION CENTRAL 110X90','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200155	,'TAPON DE 20 MM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200156	,'TAPON DE 25 MM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200157	,'TAPON DE 32 MM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200158	,'TAPON DE 40 MM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200159	,'TAPON DE 50 MM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200160	,'TAPON DE 63 MM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200161	,'TAPON DE 75 MM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200162	,'TAPON DE 90 MM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200154	,'TAPON DE 110 MM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200232	,'TUERCA UNION DE 20 x 20 MM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200233	,'TUERCA UNION DE 25 x 25 MM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200234	,'TUERCA UNION DE 32 x 32 MM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200238	,'UNION BRIDA DE 40 x 40 MM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200239	,'UNION BRIDA DE 50 x 50 MM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200240	,'UNION BRIDA DE 63 x 63 MM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200241	,'UNION BRIDA DE 75 x 75 MM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200242	,'UNION BRIDA DE 90 x 90 MM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200243	,'UNION BRIDADA DE 110 x 110 MM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200235	,'TUERCA UNION MIXTA DE 20 MM x 1/2','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200236	,'TUERCA UNION MIXTA DE 25 MM x 3/4','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200237	,'TUERCA UNION MIXTA DE 32 MM x 1','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200249	,'UNION BRIDADA MIXTA DE 40 MM x 1 1/4','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200244	,'UNION BRIDADA MIXTA DE 50 MM x 1 1/2','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200245	,'UNION BRIDADA MIXTA DE 63 MM x 2','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200246	,'UNION BRIDADA MIXTA DE 75 MM x 2 1/2','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200247	,'UNION BRIDADA MIXTA DE 90 MM x 3','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200248	,'UNION BRIDADA MIXTA DE 110 MM x 4','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200121	,'MONTURA DE DERIVACION DE 63 x 20 MM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200122	,'MONTURA DE DERIVACION DE 63 x 25 MM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200123	,'MONTURA DE DERIVACION DE 75 x 20 MM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200124	,'MONTURA DE DERIVACION DE 75 x 25 MM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200125	,'MONTURA DE DERIVACION DE 75 x 32 MM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200126	,'MONTURA DE DERIVACION DE 90 x 20 MM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200127	,'MONTURA DE DERIVACION DE 90 x 25 MM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200128	,'MONTURA DE DERIVACION DE 90 x 32 MM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200117	,'MONTURA DE DERIVACION DE 110 x 20 MM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200118	,'MONTURA DE DERIVACION DE 110 x 25 MM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200119	,'MONTURA DE DERIVACION DE 110 x 32 MM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200120	,'MONTURA DE DERIVACION DE 110 x 40 MM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200085	,'CURVA A 90 DE 20 MM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200086	,'CURVA A 90 DE 25 MM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200087	,'CURVA A 90 DE 32 MM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200088	,'CURVA DE SOBREPASAJE DE 20 MM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200089	,'CURVA DE SOBREPASAJE DE 25 MM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200090	,'CURVA DE SOBREPASAJE DE 32 MM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200250	,'VALVULA DE ESFERA DE 20 MM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200251	,'VALVULA DE ESFERA DE 25 MM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	210136	,'LLAVE PARA EMPOTRAR 20MM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	210137	,'JUEGO LLAVE REGADERA 20MM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200252	,'VALVULA DE ESFERA DESMONTABLE 20X20 MM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200253	,'VALVULA DE ESFERA DESMONTABLE 25X25 MM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200254	,'VALVULA DE ESFERA DESMONTABLE 32X32 MM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200255	,'VALVULA DE ESFERA DESMONTABLE 40X40 MM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200256	,'VALVULA DE ESFERA DESMONTABLE 50X50 MM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200257	,'VALVULA DE ESFERA DESMONTABLE 63X63 MM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200360	,'VALVULA ESFERA PPR 20MM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200361	,'VALVULA ESFERA PPR 25MM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200362	,'VALVULA ESFERA PPR 32MM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200363	,'VALVULA ESFERA PPR 40MM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200364	,'VALVULA ESFERA PPR 50MM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200365	,'VALVULA ESFERA PPR 63MM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200366	,'VALVULA ESFERA PPR 75MM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200367	,'VALVULA ESFERA PPR 90MM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200368	,'VALVULA ESFERA PPR 110MM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200668	,'VALVULA GLOBO 20MM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200667	,'VALVULA GLOBO 25MM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200666	,'VALVULA GLOBO 32MM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200372	,'VALVULA GLOBO PPR 40MM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200373	,'VALVULA GLOBO PPR 50MM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200374	,'VALVULA GLOBO PPR 63MM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200619	,'VALVULA ANGULAR FUSIONABLE','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200620	,'VALVULA ANGULAR ROSCABLE','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200073	,'COPLE ELECTRICO DE 20 MM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200074	,'COPLE ELECTRICO DE 25 MM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200075	,'COPLE ELECTRICO DE 32 MM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200076	,'COPLE ELECTRICO DE 40 MM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200077	,'COPLE ELECTRICO DE 50 MM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200078	,'COPLE ELECTRICO DE 63 MM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200079	,'COPLE ELECTRICO DE 75 MM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200080	,'COPLE ELECTRICO DE 90 MM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200279	,'CONECTOR RAPIDO A COBRE 20 X 1/2','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	320003	,'BOMBA PERIFERICA 1/2 HP.','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	320004	,'BOMBA PERIFERICA 3/4 HP','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	320001	,'BOMBA CENTRIFUGA 1/2 HP','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	320002	,'BOMBA CENTRIFUGA 3/4 HP','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	320000	,'BOMBA CENTRIFUGA 1 HP','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	320006	,'BOMBA SUMERGIBLE 1/3 HP','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	320005	,'BOMBA SUMERGIBLE 1/2 HP','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	320009	,'HIDRONEUMATICO 3/4 HP C/TANQUE DE 24 L','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	320008	,'HIDRONEUMATICO DE 1 HP C/TANQUE DE 72 L','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	320007	,'HIDRONEUMATICO DE 1 HP C/TANQUE DE 132 L','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	320010	,'SISTEMA HIDRONEUMATICO 1/2 HP CONSTRUCT','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	500023	,'SISTEMA MEJOR AGUA 450 LTS TRICAPA','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	500025	,'SISTEMA MEJOR AGUA 600 LTS TRICAPA','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	500027	,'SISTEMA MEJOR AGUA 750 LTS TRICAPA','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	500019	,'SISTEMA MEJOR AGUA 1100 LTS TRICAPA','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	500021	,'SISTEMA MEJOR AGUA 2500 LTS TRICAPA','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	500017	,'SISTEMA MEJOR AGUA 1100 LTS H.E. TRICAPA','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	500018	,'SISTEMA MEJOR AGUA 1100 LT HORIZ TRIC','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	310070	,'TAPA Y ARILLO CLICK NEGRO MX','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	310323	,'TAPA Y ARILLO CLICK NEGRO 60 CM INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (MEX)','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	510159	,'CISTERNA 1200 L NM C/BOMBA','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	510157	,'CISTERNA 2800 L NM EQUIPADA','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	510155	,'CISTERNA 5000 L NM EQUIPADA','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	510161	,'CISTERNA 10000 L NM EQUIPADA','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	510160	,'CISTERNA 1200 L NM S/BOMBA','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	510158	,'CISTERNA 2800 L NM S/EQUIPO','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	510156	,'CISTERNA 5000 L NM S/EQUIPO','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	510154	,'CISTERNA 10000 L NM S/EQUIPO','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	510175	,'CISTERNA 5000 LTS / HIDRO 24 LTS NM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	510176	,'CISTERNA 5000 LTS / HIDRO 72 LTS NM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	510177	,'CISTERNA 10000L /HIDRO 24L / FILTRO J NM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	510178	,'CISTERNA 10000L /HIDRO 72L / FILTRO J NM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	500040	,'TAMBOPLAS 250 LTS','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	310002	,'BASE PARA TINACO','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	310710	,'VALV  DE LLENADO S/ F 3/4 A 1/2INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (BLISTER)','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	310092	,'VALVULA DE LLENADO 1/2 PLG','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	310093	,'VALVULA DE LLENADO 3/4 PLG','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	310090	,'VALVULA DE ESFERA 1/2 PLG','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	310091	,'VALVULA DE ESFERA 3/4 PLG','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	310055	,'MULTICONECTOR','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	310054	,'MULTICONECTOR C/VALV-TUERCA UNION INTEG','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	310045	,'FLOTADOR # 3','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	310046	,'FLOTADOR # 5','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	310047	,'FLOTADOR # 7','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	310032	,'ELECTRONIVEL 2 MTS','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	310033	,'ELECTRONIVEL 3 MTS','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	310035	,'ELECTRONIVEL 5 MTS','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	310088	,'VALVULA DE PIE INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (PICHANCHA)','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	300003	,'FILTRO ESTANDAR','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	300000	,'CARTUCHO DE REPUESTO FILTRO ESTANDAR','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	300043	,'CARTUCHO DE REPUESTO FIL STD DUOPACK','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	300006	,'FILTRO JUMBO','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	300001	,'CARTUCHO  FILTRO JUMBO','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	300008	,'PURIFICADOR SOBRE TARJA','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	300009	,'PURIFICADOR BAJO TARJA','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	300002	,'CARTUCHO DE REPUESTO PURIFICADOR','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	300044	,'CARTUCHO DE REPUESTO PURIF DUOPACK','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	300100	,'SISTEMA DE OSMOSIS INVERSA DOMESTICO.','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	300055	,'CARTUCHO DE REPUESTO DE PP PARA OI','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	300056	,'CARTUCHO D REPUESTO CARBON A PRIMARIO OI','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	300057	,'CARTUCHO D REPUESTO CARBON A SECUNDA OI','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	300058	,'CARTUCHO DE REPUESTO DE MEMBRANA PARA OI','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	300052	,'CARTUCHO DE REPUESTO DE F P/REFRI 1 AÑO','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	300132	,'PURIFICADOR Y ALCALINIZADOR SOBRE TARJA.','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	300147	,'PURIFICADOR Y ALC. SOBRE TARJA NEGRO.','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	300139	,'CARTUCHO REP. ALC. PH 1.0 PUREAL.','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	300138	,'CARTUCHO DE REPUESTO UF PUREAL.','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	300137	,'CARTUCHO REPUESTO SEDIM.Y CARBON PUREAL.','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	310568	,'LlAVE CUELLO DE GANSO EMPAQUE NUEVO','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	520002	,'BIODIGESTOR AUTOLIMPIABLE 600 LTS','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	520000	,'BIODIGESTOR AUTOLIMPIABLE 1300 LTS','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	520001	,'FOSAPLAS AUTOLIMPIABLE 3000 LTS','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	520003	,'BIODIGESTOR AUTOLIMPIABLE 7000 LTS','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	530007	,'REGISTRO DE LODOS BDA','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	520078	,'BAÑO HÚMEDO LT C / BIODI AUTOLIMPIABLE','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	520079	,'BAÑO HUMEDO LT CON DUCHA','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200282	,'TERMOFUSOR 600 WATTS INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (CON ACCESORIOS)','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200110	,'KIT DE TERMOFUSOR 800W C/COMPONENTES','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200208	,'TERMOFUSOR RJQ 110 120V-1200W S/DADOS','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200266	,'PLANTA GENERADORA DE ENERGIA TUBOPLUS','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200214	,'TIJERAS CORTATUBO HASTA 32','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200216	,'TIJERAS CORTATUBO 40 MM HEAVY DUTY','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200215	,'TIJERAS CORTATUBO HASTA 63','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200261	,'Cortatubo Rothemberger 127 mm','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200092	,'DADOS M H DE 20 MM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200093	,'DADOS M H DE 25 MM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200094	,'DADOS M H DE 32 MM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200095	,'DADOS M H DE 40 MM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200096	,'DADOS M H DE 50 MM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200097	,'DADOS M H DE 63 MM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200098	,'DADOS M H DE 75 MM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200099	,'DADOS M H DE 90 MM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200091	,'DADOS M H DE 110 MM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200107	,'DADOS PARA REPARACION','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200280	,'TAPON DE REPARACION','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200133	,'PINZA PARA EXTRACCION DE DADOS','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200218	,'TORNILLO ALLEN ACERO GALV 5/16-18 UNCX2.','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200112	,'LLAVE ALLEN PARA AJUSTE DE DADOS','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200130	,'PERFORADOR P/MONTURAS DERIVACION  20/25','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200131	,'PERFORADOR P/ MONTURAS DE DERIVACION 32','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200102	,'DADOS MONTURAS DE DERIVACION 63 x 20/25','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200103	,'DADOS MONTURAS DE DERIVACION 75 x 20/25.','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200105	,'DADOS MONTURAS DE DERIVACION 90 x 20/25.','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200104	,'DADOS MONTURA DE DERIVACION 75 x 32','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200106	,'DADOS MONTURA DE DERIVACION 90 x 32','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200100	,'DADOS MONTURAS DE DERIVACION 110 x 20','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (	10	,	200101	,'DADOS MONTURA DE DERIVACION 110 x 32','PZA','');
