INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (11,560041,'TOLVA 600 L ANGULO 45 REF 40% NEUTRA','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (11,560006,'TOLVA 1300 L ANGULO 45 STD NEGRA','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (11,560007,'TOLVA 1300 L ANGULO 45 STD NEUTRA','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (11,560010,'TOLVA 1300 L ANGULO 45 REF 40% NEGRO','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (11,5600INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (11,'TOLVA 1300 L ANGULO 45 REF 40% NEUTRA','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (11,560026,'TOLVA 3000 L ANGULO 15 STD NEUTRA','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (11,560030,'TOLVA 3500 L ANGULO 45 STD NEUTRA','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (11,560035,'TOLVA 3500 L ANGULO 45 REF 40% NEUTRA','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (11,560043,'TOLVA 7000 L ANGULO 45 STD NEGRA','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (11,560044,'TOLVA 7000 L ANGULO 45 STD NEUTRA','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (11,560047,'TOLVA 7000 L ANGULO 45 REF 40% NEGRA','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (11,560048,'TOLVA 7000 L ANGULO 45 REF 40% NEUTRA','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (11,560056,'TOLVA 14000 L 60° P/GRANOS NEGRO','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (11,560019,'TOLVA 14000 L ANGULO 60 P/LIQ STD NEUTRA','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (11,560022,'TOLVA 14000 L ANG 60 REF 40% P/GRANO NEU','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (11,560023,'TOLVA 14000 L ANG 60 REF 40% P/LIQ NEGRA','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (11,570013,'PESEBRE 120 L NEGRO','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (11,570007,'BEBEDERO 300 L STD NEGRO BECOSA','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (11,570008,'BEBEDERO 500 L STD NEGRO HORIZONTAL','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (11,570012,'BEBEDERO 850 L STD NEGRO TIPO CANOA','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (11,570003,'BEBEDERO 1000 L STD NEGRO BD','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (11,570004,'BEBEDERO 1700 L STD NEGRO HD','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (11,550019,'TNH 1000 L STD NEGRO','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (11,550020,'TNH 1000 L STD NEUTRO','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (11,550021,'TNH 1000 L REF 20% NEGRO','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (11,550022,'TNH 1000 L REF 20% NEUTRO','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (11,550023,'TNH 1000 L REF 40% NEGRO','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (11,550024,'TNH 1000 L REF 40% NEUTRO','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (11,550008,'TNE 2500 L STD NEGRO','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (11,550009,'TNE 2500 L STD NEUTRO','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (11,550010,'TNE 2500 L REF 20% NEGRO','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (11,5500INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (11,'TNE 2500 L REF 20% NEUTRA','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (11,550188,'TNE 2500 L REF 40% NEGRO','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (11,550012,'TNE 2500 L REF 40% NEUTRA','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (11,550025,'TNH 2850 L STD NEGRO','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (11,550026,'TNH 2850 L STD NEUTRO','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (11,550027,'TNH 2850 L REF 20% NEGRO','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (11,550028,'TNH 2850 L REF 20% NEUTRO','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (11,550029,'TNH 2850 L REF 40% NEGRO','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (11,550030,'TNH 2850 L REF 40% NEUTRO','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (11,550013,'TNE 4000 L STD NEGRO','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (11,550014,'TNE 4000 L STD NEUTRO','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (11,550015,'TNE 4000 L REF 20% NEGRO','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (11,550016,'TNE 4000 L REF 20% NEUTRO','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (11,550017,'TNE 4000 L REF 40% NEGRO','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (11,550018,'TNE 4000 L REF 40% NEUTRO','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (11,550031,'TNH 5000 L STD NEGRO','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (11,550032,'TNH 5000 L STD NEUTRO','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (11,550033,'TNH 5000 L REF 20% NEGRO','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (11,550034,'TNH 5000 L REF 20% NEUTRO','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (11,550035,'TNH 5000 L REF 40% NEGRO','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (11,550036,'TNH 5000 L REF 40% NEUTRO','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (11,550000,'THAA 600 L STD NEUTRO','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (11,550142,'TVC 450 L STD NEGRO','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (11,550143,'TVC 450 L STD NEUTRO','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (11,550146,'TVC 450 L REF 40% NEGRO','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (11,550147,'TVC 450 L REF 40% NEUTRO','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (11,550148,'TVC 600 L ESTANDAR NEUTRO','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (11,550149,'TVC 600 L STD NEGRO','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (11,550152,'TVC 600 L REF 40% NEUTRO','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (11,550153,'TVC 600 L REF 40% NEGRO','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (11,550154,'TVC 750 L STD NEGRO','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (11,550155,'TVC 750 L STD NEUTRO','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (11,550158,'TVC 750 L REF 40% NEUTRO','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (11,550159,'TVC 750 L REF 40% NEGRO','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (11,550130,'TVC 1100 L STD NEGRO','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (11,550131,'TVC 1100 L STD NEUTRO','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (11,550134,'TVC 1100 L REF 40% NEGRO','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (11,550135,'TVC 1100 L REF 40% NEUTRO','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (11,550136,'TVC 2500 L STD NEGRO','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (11,550137,'TVC 2500 L STD NEUTRO','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (11,550140,'TVC 2500 L REF 40% NEGRO','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (11,550141,'TVC 2500 L REF 40% NEUTRO','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (11,550160,'TVC 250 L STD NEGRO','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (11,550161,'TVC 250 L STD NEUTRO','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (11,550164,'TVC 250 L REF 40% NEGRO','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (11,550165,'TVC 250 L REF 40% NEUTRO','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (11,210059,'COLADERA DE BAÑO C/ REJILLA  DE  METAL','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (11,210058,'COLADERA  DE  AZOTEA','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (11,110693,'REJILLA  DE  METAL  CON  TORNILLOS','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (11,210060,'COLADERA DE BAÑO C/REJILLA DE PLASTICO','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (11,210061,'COLADERA BAÑO C/REJILLA PLASTI BAJO LOSA','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (11,210062,'COLADERA  DE  PATIO','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (11,210012,'ADAPTADOR P/PVC 40 MM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (11,210013,'ADAPTADOR P/PVC 50 MM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (11,210014,'ADAPTADOR P/PVC 75 MM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (11,210010,'ADAPTADOR P/PVC 110 MM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (11,2100INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (11,'ADAPTADOR P/PVC 160 MM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (11,210015,'ADAPTADOR P/PVC C/ESPIGA 110 MM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (11,210016,'ADAPTADOR P/PVC C/ESPIGA 160 MM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (11,210017,'ADAPTADOR P/PVC C/ESPIGA 40 MM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (11,210018,'ADAPTADOR P/PVC C/ESPIGA 50 MM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (11,210019,'ADAPTADOR P/PVC C/ESPIGA 75 MM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (11,210160,'ADAPTADOR P/PVC 40 MM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (11,210161,'ADAPTADOR P/PVC 50 MM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (11,530008,'REG SANITARIO TAPA CIEGA 4 PLG X 45 CM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (11,530009,'REG SANITARIO TAPA CIEGA 4 PLG X 70 CM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (11,530010,'REG SANITARIO TAPA CIEGA 4 PLG X 100 CM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (11,5300INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (11,'REG SANITARIO C/TAPA CIEGA 6 PLG X 45 CM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (11,530012,'REG SANITARIO TAPA CIEGA 6 PLG X 70 CM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (11,530013,'REG SAN.ITARIO TAPA CIEGA 6 PLG X 100 CM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (11,530014,'REG SANIT. TAPA C/COLADERA 4 PLG X 45 CM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (11,530015,'REG SANIT. TAPA C/COLADERA 4 PLG X 70 CM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (11,530016,'REG SANIT TAPA C/COLADERA 4 PLG X 100 CM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (11,530017,'REG SANIT TAPA C/ COLADERA 6 PLG X 45 CM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (11,530018,'REG SANIT TAPA C/ COLADERA 6 PLG X 70 CM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (11,530019,'REG SANIT TAPA C/COLADERA 6 PLG X 100 CM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (11,200285,'CORTACIRCULO C/ADAP BI-METAL 127 MM','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (11,210074,'EMPAQUE MEMBRANA PARA TUBOS DE 40 A 110','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (11,111182,'ORING DE 110 MM PARA REGISTRO SANITARIO','PZA','');
INSERT INTO [PortalClientes].[dbo].[Material] (tipoMaterial,sku,descripcion,unidadMedida,urlFoto) VALUES (11,111183,'ORING DE 160 MM PARA REGISTRO SANITARIO','PZA','');
